=== dSafaReyes/XML/src/main/java/xsd/UXMLS-5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="periodista" type="xs:string"/>
    <xs:element name="titular" type="xs:string"/>

    <xs:attribute name="dia" type="xs:gDay"/>
    <xs:attribute name="mes" type="xs:gMonth"/>
    <xs:attribute name="año" type="xs:gYear"/>
    <xs:attribute name="seccion" type="xs:string"/>

    <xs:element name="medio">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="tipo">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="radio"/>
                                <xs:enumeration value="prensa"/>
                                <xs:enumeration value="televisión"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="resumen" type="xs:string">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="60"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Noticia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="medio"/>
                <xs:element ref="periodista"/>
                <xs:element ref="titular"/>
                <xs:element ref="resumen"/>
            </xs:sequence>
            <xs:attribute ref="dia"/>
            <xs:attribute ref="mes"/>
            <xs:attribute ref="año"/>
            <xs:attribute ref="seccion"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Noticias">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Noticia" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dSafaReyes/XML/src/main/java/xsd/xml-5.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Noticias  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="UXMLS-5.xsd">

    <Noticia dia="---12" mes="--03--" año="2004" seccion="Nacional">
        <medio tipo="prensa">Onda Cero</medio>
        <periodista>Fermín Bocos</periodista>
        <titular>Atentado bestial en Madrid</titular>
        <resumen>Resumen de la noticia "Atentado bestial en Madrid"</resumen>
    </Noticia>

    <Noticia dia="---15" mes="--03--" año="2004" seccion="Economía">
        <medio tipo="prensa">ABC</medio>
        <periodista>Juan Iranzo</periodista>
        <titular>La Bolsa no da la bienvenida al nuevo gobierno</titular>
        <resumen>Resumen de la noticia "La Bolsa no da la bienvenida al nuevo gobierno"</resumen>
    </Noticia>

    <Noticia dia="---15" mes="--03--" año="2004" seccion="Nacional">
        <medio tipo="televisión">Radio Nacional</medio>
        <periodista>Magín Revillo</periodista>
        <titular>Vuelco electoral en España</titular>
        <resumen>Resumen de la noticia "Vuelco electoral en España"</resumen>
    </Noticia>

    <Noticia dia="---23" mes="--03--" año="2004" seccion="Internacional">
        <medio tipo="prensa">La Vanguardia</medio>
        <periodista>Luis Foix</periodista>
        <titular>John Kerry se postula como rival de Bush</titular>
        <resumen>Resumen de la noticia "John Kerry se postula como rival de Bush"</resumen>
    </Noticia>

    <Noticia dia="---23" mes="--03--" año="2004" seccion="Internacional">
        <medio tipo="televisión">Tele 5</medio>
        <periodista>Juan Pedro Valentín</periodista>
        <titular>Disturbios en Puerto Príncipe tras la marcha de Aristide</titular>
        <resumen>Resumen de la noticia "Disturbios en Puerto Príncipe tras la marcha de Aristide"</resumen>
    </Noticia>

    <Noticia dia="---23" mes="--03--" año="2004" seccion="Deportes">
        <medio tipo="televisión">La 2</medio>
        <periodista>Fran Llorente</periodista>
        <titular>La granadina María José Rienda, segunda en el Mundial de Esquí</titular>
        <resumen>Resumen de la noticia "La granadina María José Rienda, segunda en el Mundial de Esquí"</resumen>
    </Noticia>

</Noticias>
