=== dSafaReyes/XML/src/main/java/xsd/UXMLS-6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--    <xs:element name="Disponible" type="xs:string"/>-->
    <xs:element name="Codigo" type="xs:string"/>
    <xs:element name="Fabricante" type="xs:string"/>
    <xs:element name="Comentario" type="xs:string"/>

    <xs:attribute name="Género" type="xs:string"/>
    <xs:attribute name="Año" type="xs:gYear"/>
    <xs:attribute name="Compat" type="xs:string"/>
    <xs:attribute name="Tecno" type="xs:string"/>
    <xs:attribute name="Magnitud" type="xs:string"/>


    <xs:element name="Titulo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="Compat"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Tamaño">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="Magnitud"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Edad">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:maxInclusive value="12"/>
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Disponible">
        <xs:complexType>
            <xs:complexContent>
                <xs:restriction base="xs:string">
                    <xs:attribute name="Tecno"/>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

<!--    <xs:element name="Disponible">-->
<!--        <xs:complexType>-->
<!--            <xs:attribute ref="Tecno"/>-->
<!--        </xs:complexType>-->
<!--    </xs:element>-->

    <xs:element name="Precio">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="Moneda">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="euros"/>
                                <xs:enumeration value="dólares"/>
                                <xs:enumeration value="yenes"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Juego">
        <xs:complexType>
            <xs:sequence>
                    <xs:element ref="Titulo"/>
                    <xs:element ref="Codigo" minOccurs="0"/>
                    <xs:element ref="Disponible" maxOccurs="unbounded" minOccurs="0"/>
                    <xs:element ref="Fabricante" minOccurs="0"/>
                    <xs:element ref="Tamaño" minOccurs="0"/>
                    <xs:element ref="Precio"/>
                    <xs:element ref="Edad"/>
                    <xs:element ref="Comentario"/>
            </xs:sequence>
            <xs:attribute ref="Género"/>
            <xs:attribute ref="Año"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Videojuegos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Juego" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Ocio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Videojuegos" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dSafaReyes/XML/src/main/java/xsd/xml-6.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Ocio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="UXMLS-6.xsd">
    <Videojuegos>

        <Juego Género="Arcade" Año="2004">
            <Titulo Compat="PC">Bandits Phoenix Rising</Titulo>
            <Codigo>AC-135 ONT</Codigo>
            <Fabricante>PAN VISION</Fabricante>
            <Precio Moneda="euros">40</Precio>
            <Edad>6</Edad>
            <Comentario>Estás a punto de entrar en el mundo de Bandits - Phoenix Rising. un mundo de tipos duros que
                luchan por sobrevivir; bandas motorizadas de bandidos que imponen su ley combatiendo por el com...</Comentario>
        </Juego>

        <Juego Género="Acción" Año="2005">
            <Titulo Compat="PC">Battlefield 2</Titulo>
            <Codigo>SC-246 PXD</Codigo>
            <Disponible Tecno="PS2"/>
            <Disponible Tecno="GCUBE"/>
            <Disponible Tecno="XBOX"/>
            <Fabricante>Digital Illusions</Fabricante>
            <Tamaño Magnitud="MB">11.8</Tamaño>
            <Precio Moneda="euros">39</Precio>
            <Edad>1</Edad>
            <Comentario>La continuación de uno de los juegos de acción multijugador más sorprendentes y adictivos de
                los últimos años, pero esta vez dejando atrás a la Segunda Guerra Mundial y preparándonos ...</Comentario>
        </Juego>

        <Juego Género="Deportes" Año="2005">
            <Titulo Compat="GBA">FIFA Football 2005</Titulo>
            <Codigo>AA-198 URF</Codigo>
            <Fabricante>EA Sports</Fabricante>
            <Precio Moneda="euros">46.95</Precio>
            <Edad>12</Edad>
            <Comentario>Y por fin llegamos al año en el que supuestamente Electronic Arts nos iba a regalar el mejor
                FIFA, el juego de fútbol definitivo. Desde el punto de penalti, y con la clásica controversia de por
                medio...</Comentario>
        </Juego>

        <Juego Género="Estrategia" Año="2004">
            <Titulo Compat="PC">IMPERIUM III</Titulo>
            <Disponible Tecno="PS2"/>
            <Disponible Tecno="GBA"/>
            <Fabricante>FX Interactive</Fabricante>
            <Precio Moneda="euros">19.95</Precio>
            <Edad>12</Edad>
            <Comentario>Augusto desembarca en egipto tras vencer a marco antonio y clepatra en la batalla naval de
                Actium. Viriato mantiene en jaque a las legiones en Hispania. Marco Aurelio se enfrenta a los
                germanos...</Comentario>
        </Juego>

        <Juego Género="Rol" Año="2004">
            <Titulo Compat="PC">Piratas del Caribe</Titulo>
            <Disponible Tecno="PS2"/>
            <Disponible Tecno="GBA"/>
            <Fabricante>Betsheda</Fabricante>
            <Precio Moneda="euros">19.95</Precio>
            <Edad>12</Edad>
            <Comentario>El Capitán Nathaniel Hawk es testigo de la invasión de una isla inglesa por ...</Comentario>
        </Juego>

    </Videojuegos>
</Ocio>
